/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u6p1;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import u6p1.ClasesJ.ConexionMysql;

/**
 *
 * @author reyes
 */
public class Inserta extends javax.swing.JFrame {

    /**
     * Creates new form Inserta
     */
    public Inserta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Id_trabA = new javax.swing.JTextField();
        Id_obraA = new javax.swing.JTextField();
        Dias = new javax.swing.JTextField();
        msg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Id_obra = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Tipo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        Id_trab = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Sueldo = new javax.swing.JTextField();
        Oficio = new javax.swing.JComboBox<>();
        msg1 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Id_trab:");

        jLabel10.setText("Id_obra:");

        jLabel11.setText("Días:");

        Id_trabA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Id_trabAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Id_trabAKeyTyped(evt);
            }
        });

        Id_obraA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Id_obraAKeyTyped(evt);
            }
        });

        Dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DiasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Id_trabA, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Id_obraA)
                    .addComponent(Dias))
                .addGap(18, 18, 18)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(Id_trabA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Id_obraA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignación", jPanel1);

        jLabel6.setText("Id_obra:");

        jLabel7.setText("Dirección:");

        jLabel8.setText("Tipo:");

        Id_obra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Id_obraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Id_obra, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Id_obra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Obra", jPanel2);

        jLabel1.setText("Id_trab:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Sueldo_hr:");

        jLabel4.setText("Fecha_ingreso:");

        jLabel5.setText("Oficio:");

        Fecha.setDateFormatString("y-MM-dd");

        Id_trab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Id_trabKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Id_trabKeyTyped(evt);
            }
        });

        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        Sueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SueldoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SueldoKeyTyped(evt);
            }
        });

        Oficio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARPINTERO", "FONTANERO", "HERRERO", "ELECTRICO" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Oficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 190, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Sueldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Id_trab, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msg2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Id_trab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msg2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Oficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajador", jPanel3);

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Id_trabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_trabKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
                && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_Id_trabKeyTyped

    private void SueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SueldoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
                && caracter != KeyEvent.VK_BACK_SPACE
                && (caracter != '.' || Sueldo.getText().contains("."))) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_SueldoKeyTyped

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if (!Character.isLetter(caracter)
                && caracter != KeyEvent.VK_SPACE
                && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int tab = jTabbedPane1.getSelectedIndex();

            mysql = new ConexionMysql("obras");
            mysql.conectar();

            if (tab == 0) {
                values = Id_trabA.getText() + ",'" + Id_obraA.getText() + "'," + Dias.getText();
                Id_trabA.setText("");
                Id_obraA.setText("");
                Dias.setText("");
            }
            if (tab == 1) {
                values = "'" + Id_obra.getText() + "','" + Direccion.getText() + "','" + Tipo.getText() + "'";
                Id_obra.setText("");
                Direccion.setText("");
                Tipo.setText("");
            }
            if (tab == 2) {
                Date fecha = Fecha.getDate();
                DateFormat f = new SimpleDateFormat(Fecha.getDateFormatString());
                String fecha2 = f.format(fecha);
                values = Id_trab.getText() + ",'" + Nombre.getText() + "'," + Sueldo.getText() + ",'"
                        + fecha2 + "','" + Oficio.getItemAt(Oficio.getSelectedIndex()) + "'";
                Id_trab.setText("");
                Nombre.setText("");
                Sueldo.setText("");
            }
            
            if (mysql.insertar(tabla[tab], values)) {
                    JOptionPane.showMessageDialog(this, "Insercion Exitosa");
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error en la insercion", "Error", JOptionPane.WARNING_MESSAGE);
                }
            
            mysql.desconectar();
        } catch (Exception e) {
            System.out.print("Error: \n"+e.getMessage());
            mysql.desconectar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiasKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
                && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_DiasKeyTyped

    private void Id_trabAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_trabAKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
                && caracter != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_Id_trabAKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConsultaFrame frame = new ConsultaFrame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Id_obraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_obraKeyTyped
        // TODO add your handling code here:
        if(Id_obra.getText().length() >= 4){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_Id_obraKeyTyped

    private void Id_obraAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_obraAKeyTyped
        // TODO add your handling code here:
        if(Id_obraA.getText().length() >= 4){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_Id_obraAKeyTyped

    private void Id_trabAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_trabAKeyReleased
        // TODO add your handling code here:
        int id;
        if("".equals(Id_trabA.getText())){
            msg.setText("");
            Id_trabA.setBackground(Color.white);
        }
        else{
            id = Integer.parseInt(Id_trabA.getText());
            if(id >= 10 && id <= 5000){
                msg.setText("");
                Id_trabA.setBackground(Color.white); 
            }else{
                msg.setText("Id_trab entre 10 y 5000");
                Id_trabA.setBackground(Color.red); 
            }
        }
    }//GEN-LAST:event_Id_trabAKeyReleased

    private void Id_trabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_trabKeyReleased
        // TODO add your handling code here:
        int id;
        if("".equals(Id_trab.getText())){
            msg1.setText("");
            Id_trab.setBackground(Color.white);
        }
        else{
            id = Integer.parseInt(Id_trab.getText());
            if(id >= 10 && id <= 5000){
                msg1.setText("");
                Id_trab.setBackground(Color.white); 
            }else{
                msg1.setText("Id_trab entre 10 y 5000");
                Id_trab.setBackground(Color.red); 
            }
        }
    }//GEN-LAST:event_Id_trabKeyReleased

    private void SueldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SueldoKeyReleased
        // TODO add your handling code here:
        double sueldo;
        if("".equals(Sueldo.getText())){
            msg2.setText("");
            Sueldo.setBackground(Color.white);
        }
        else{
            sueldo = Double.parseDouble(Sueldo.getText());
            if(sueldo >= 2000 && sueldo <= 40000){
                msg2.setText("");
                Sueldo.setBackground(Color.white);
            }else{
                msg2.setText("Sueldo_hr entre 2000 y 40000");
                Sueldo.setBackground(Color.red);
            }
        }
    }//GEN-LAST:event_SueldoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inserta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dias;
    private javax.swing.JTextField Direccion;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JTextField Id_obra;
    private javax.swing.JTextField Id_obraA;
    private javax.swing.JTextField Id_trab;
    private javax.swing.JTextField Id_trabA;
    private javax.swing.JTextField Nombre;
    private javax.swing.JComboBox<String> Oficio;
    private javax.swing.JTextField Sueldo;
    private javax.swing.JTextField Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    // End of variables declaration//GEN-END:variables
    private ConexionMysql mysql;
    private String values;
    private String[] tabla = {"asignacion", "obra", "trabajador"};
}
